micronaut:
  application:
    name: accounts
consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
kafka.bootstrap.servers: localhost:9092
