scrape_configs:
  - job_name: 'orders'
    scrape_interval: 15s
    scheme: http
    tls_config:
      insecure_skip_verify: true
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.100.7:8002']
